# Before run this docker compose file, check env variables
# inside .env file.
##########################################################
# Run this file on terminal using docker compose V2:
# => docker compose run --rm app

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${MIX_ENV}
      args:
        - ARG_APP_NAME=${APP_NAME}
    image: ${APP_NAME}:${MIX_ENV}
    env_file: .env.container
    container_name: ${APP_NAME}
    stdin_open: true
    tty: true
    command: sh docker/start.sh
    volumes:
      - .:/${APP_NAME} # it doesn't save the volume folder inside the docker image after builded
