# fly.toml file generated for currency-reader on 2023-03-12T22:31:32-03:00

app = "currency-reader"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"
processes = []

[env]

[build]
  build-target = "prod"

[build.args]
  ARG_APP_NAME="currency_reader"

[experimental]
  auto_rollback = true

# [[services]]
#   http_checks = []
#   internal_port = 8080
#   processes = ["app"]
#   protocol = "tcp"
#   script_checks = []
#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#     type = "connections"

#   [[services.ports]]
#     force_https = true
#     handlers = ["http"]
#     port = 80

#   [[services.ports]]
#     handlers = ["tls", "http"]
#     port = 443

#   [[services.tcp_checks]]
#     grace_period = "1s"
#     interval = "15s"
#     restart_limit = 0
#     timeout = "2s"
